; Скрипт для копирования выбранных пользователем объектов на заданную высоту в nanoCAD
(defun C:CopyToHeight (/ ss height pt1 pt2)
  (vl-load-com) ; Загружаем ActiveX интерфейс
  
  ; Запрашиваем у пользователя высоту смещения
  (setq height (getreal "\nВведите высоту смещения: "))
  
  ; Проверяем, что высота введена
  (if height
    (progn
      ; Запрашиваем у пользователя выбор объектов
      (princ "\nВыберите объекты для копирования: ")
      (setq ss (ssget)) ; Оставляем пользователю выбор объектов
      
      ; Если есть выбранные объекты
      (if ss
        (progn
          ; Задаем начальную и конечную точки смещения
          (setq pt1 '(0.0 0.0 0.0)) ; Начальная точка (0,0,0)
          (setq pt2 (list 0.0 0.0 height)) ; Конечная точка с учетом высоты
          
          ; Выполняем копирование со смещением
          (command "_COPY" ss "" pt1 pt2)
          
          (princ "\nОбъекты успешно скопированы на заданную высоту!")
        )
        (princ "\nОбъекты не выбраны!")
      )
    )
    (princ "\nВысота не была введена!")
  )
  (princ) ; Завершаем чисто
)

(princ "\nКоманда COPYTOHEIGHT загружена. Введите COPYTOHEIGHT для запуска.")
(princ)